/*
 * GroupSetupPanel.java
 *
 * Created on 30. Dezember 2005, 22:06
 */

package championship.manager;

/**
 *
 * @author  Roman Georg Rädle
 */
public class GroupSetupPanel extends javax.swing.JPanel {
    
    /** Creates new form GroupSetupPanel */
    public GroupSetupPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        groupL = new javax.swing.JLabel();
        groupCB = new javax.swing.JComboBox();
        teamsSP = new javax.swing.JScrollPane();
        teamsP = new javax.swing.JPanel();
        team1L = new javax.swing.JLabel();
        team1TF = new javax.swing.JTextField();
        team2L = new javax.swing.JLabel();
        team2TF = new javax.swing.JTextField();

        groupL.setText("Gruppe");

        groupCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        team1L.setText("1.");

        team1TF.setPreferredSize(new java.awt.Dimension(60, 19));

        team2L.setText("2.");

        org.jdesktop.layout.GroupLayout teamsPLayout = new org.jdesktop.layout.GroupLayout(teamsP);
        teamsP.setLayout(teamsPLayout);
        teamsPLayout.setHorizontalGroup(
            teamsPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, teamsPLayout.createSequentialGroup()
                .addContainerGap()
                .add(teamsPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, teamsPLayout.createSequentialGroup()
                        .add(team1L)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(team1TF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, teamsPLayout.createSequentialGroup()
                        .add(team2L)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(team2TF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                .addContainerGap())
        );
        teamsPLayout.setVerticalGroup(
            teamsPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, teamsPLayout.createSequentialGroup()
                .addContainerGap()
                .add(teamsPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(team1L)
                    .add(team1TF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamsPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(team2L)
                    .add(team2TF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        teamsSP.setViewportView(teamsP);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(teamsSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(groupL)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(groupCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(groupL)
                    .add(groupCB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamsSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox groupCB;
    private javax.swing.JLabel groupL;
    private javax.swing.JLabel team1L;
    private javax.swing.JTextField team1TF;
    private javax.swing.JLabel team2L;
    private javax.swing.JTextField team2TF;
    private javax.swing.JPanel teamsP;
    private javax.swing.JScrollPane teamsSP;
    // End of variables declaration//GEN-END:variables
    
}
