/*
 * PlayPanel.java
 *
 * Created on 30. Dezember 2005, 22:29
 */

package championship.manager;

/**
 *
 * @author  Roman Georg Rädle
 */
public class PlayPanel extends javax.swing.JPanel {
    
    /** Creates new form PlayPanel */
    public PlayPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        gamesSP = new javax.swing.JScrollPane();
        gamesT = new javax.swing.JTable();
        calculateB = new javax.swing.JButton();
        saveB = new javax.swing.JButton();

        gamesT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gamesSP.setViewportView(gamesT);

        calculateB.setText("Vorrunde berechnen");

        saveB.setText("Speichern");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(gamesSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(calculateB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(saveB)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {calculateB, saveB}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(calculateB)
                    .add(saveB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(gamesSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateB;
    private javax.swing.JScrollPane gamesSP;
    private javax.swing.JTable gamesT;
    private javax.swing.JButton saveB;
    // End of variables declaration//GEN-END:variables
    
}
