/*
 * SettupPanel.java
 *
 * Created on 30. Dezember 2005, 20:26
 */

package championship.manager;

/**
 *
 * @author  Roman Georg Rädle
 */
public class SetupDialog extends javax.swing.JPanel {
    
    /** Creates new form SettupPanel */
    public SetupDialog() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        okB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        applyB = new javax.swing.JButton();
        setupTP = new javax.swing.JTabbedPane();

        okB.setText("OK");

        cancelB.setText("Abbrechen");

        applyB.setText("\u00dcbernehmen");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(setupTP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(okB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(applyB)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {applyB, cancelB, okB}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(setupTP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 334, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(applyB)
                    .add(cancelB)
                    .add(okB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyB;
    private javax.swing.JButton cancelB;
    private javax.swing.JButton okB;
    private javax.swing.JTabbedPane setupTP;
    // End of variables declaration//GEN-END:variables
    
}
