/*
 * TablePanel.java
 *
 * Created on 2. Januar 2006, 17:14
 */

package championship.manager;

/**
 *
 * @author  Roman Georg Rädle
 */
public class ShowTablePanel extends javax.swing.JPanel {
    
    /** Creates new form TablePanel */
    public ShowTablePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tableSP = new javax.swing.JScrollPane();
        tableT = new javax.swing.JTable();
        groupL = new javax.swing.JLabel();

        tableT.setFont(new java.awt.Font("Tahoma", 1, 18));
        tableT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableT.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableT.setShowHorizontalLines(false);
        tableT.setShowVerticalLines(false);
        tableSP.setViewportView(tableT);

        groupL.setFont(new java.awt.Font("Tahoma", 1, 24));
        groupL.setText("Aktuelle Tabelle Gruppe A");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(groupL)
                    .add(tableSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(groupL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tableSP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel groupL;
    private javax.swing.JScrollPane tableSP;
    private javax.swing.JTable tableT;
    // End of variables declaration//GEN-END:variables
    
}
