/*
 * ShowGameTablePanel.java
 *
 * Created on 2. Januar 2006, 17:13
 */

package championship.manager;

/**
 *
 * @author  Roman Georg Rädle
 */
public class ShowGameTablePanel extends javax.swing.JPanel {
    
    /** Creates new form ShowGameTablePanel */
    public ShowGameTablePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        showTableP = new championship.manager.ShowTablePanel();
        lastB = new javax.swing.JButton();
        nextB = new javax.swing.JButton();
        hometeamL = new javax.swing.JLabel();
        hometeamPB = new javax.swing.JButton();
        hometeamMB = new javax.swing.JButton();
        awayteamL = new javax.swing.JLabel();
        awayteamPB = new javax.swing.JButton();
        awayteamMB = new javax.swing.JButton();
        gameL = new javax.swing.JLabel();
        currentHometeamL = new javax.swing.JLabel();
        currentAwayteamL = new javax.swing.JLabel();
        sizeL = new javax.swing.JLabel();
        sizePB = new javax.swing.JButton();
        sizeMB = new javax.swing.JButton();
        countingWatchL = new javax.swing.JLabel();
        startCountingWatchB = new javax.swing.JButton();
        stopCountingWatchB = new javax.swing.JButton();
        resetCountingWatchB = new javax.swing.JButton();
        countingWatchP = new javax.swing.JPanel();

        lastB.setText("<<");

        nextB.setText(">>");

        hometeamL.setText("SV Ennetach");

        hometeamPB.setText("+");

        hometeamMB.setText("-");

        awayteamL.setText("FV Weithart");

        awayteamPB.setText("+");

        awayteamMB.setText("-");

        gameL.setText("Spiel-Nr. 1");

        currentHometeamL.setFont(new java.awt.Font("Tahoma", 1, 56));
        currentHometeamL.setText("3    SV Ennetach");
        currentHometeamL.setIconTextGap(0);

        currentAwayteamL.setFont(new java.awt.Font("Tahoma", 1, 56));
        currentAwayteamL.setText("1    FV Weithart");
        currentAwayteamL.setIconTextGap(0);

        sizeL.setText("Schriftgr\u00f6\u00dfe");

        sizePB.setText("+");

        sizeMB.setText("-");

        countingWatchL.setText("Stoppuhr");

        startCountingWatchB.setText("Start");

        stopCountingWatchB.setText("Stop");

        resetCountingWatchB.setText("Reset");

        org.jdesktop.layout.GroupLayout countingWatchPLayout = new org.jdesktop.layout.GroupLayout(countingWatchP);
        countingWatchP.setLayout(countingWatchPLayout);
        countingWatchPLayout.setHorizontalGroup(
            countingWatchPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 152, Short.MAX_VALUE)
        );
        countingWatchPLayout.setVerticalGroup(
            countingWatchPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 110, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(showTableP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .add(currentAwayteamL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .add(currentHometeamL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lastB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, nextB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(gameL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(45, 45, 45)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(hometeamPB)
                            .add(hometeamL)
                            .add(hometeamMB))
                        .add(56, 56, 56)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(awayteamMB)
                            .add(awayteamPB)
                            .add(awayteamL))
                        .add(58, 58, 58)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(sizeL)
                            .add(sizePB)
                            .add(sizeMB))
                        .add(73, 73, 73)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(countingWatchL)
                            .add(startCountingWatchB)
                            .add(stopCountingWatchB)
                            .add(resetCountingWatchB))
                        .add(41, 41, 41)
                        .add(countingWatchP)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {sizeMB, sizePB}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {awayteamMB, awayteamPB, hometeamMB, hometeamPB}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {resetCountingWatchB, startCountingWatchB, stopCountingWatchB}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(hometeamL)
                                    .add(gameL))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(lastB)
                                    .add(hometeamPB))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(nextB)
                                    .add(hometeamMB)))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(awayteamL)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(awayteamPB)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(awayteamMB))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(sizeL)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(sizePB)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(sizeMB))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(countingWatchL)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(startCountingWatchB)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(stopCountingWatchB)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(resetCountingWatchB))
                    .add(countingWatchP))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentHometeamL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentAwayteamL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(showTableP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel awayteamL;
    private javax.swing.JButton awayteamMB;
    private javax.swing.JButton awayteamPB;
    private javax.swing.JLabel countingWatchL;
    private javax.swing.JPanel countingWatchP;
    private javax.swing.JLabel currentAwayteamL;
    private javax.swing.JLabel currentHometeamL;
    private javax.swing.JLabel gameL;
    private javax.swing.JLabel hometeamL;
    private javax.swing.JButton hometeamMB;
    private javax.swing.JButton hometeamPB;
    private javax.swing.JButton lastB;
    private javax.swing.JButton nextB;
    private javax.swing.JButton resetCountingWatchB;
    private championship.manager.ShowTablePanel showTableP;
    private javax.swing.JLabel sizeL;
    private javax.swing.JButton sizeMB;
    private javax.swing.JButton sizePB;
    private javax.swing.JButton startCountingWatchB;
    private javax.swing.JButton stopCountingWatchB;
    // End of variables declaration//GEN-END:variables
    
}
